# Generated by Django 5.0.6 on 2024-06-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coords",
            new_name="Coord",
        ),
        migrations.RenameModel(
            old_name="Images",
            new_name="Image",
        ),
        migrations.RenameModel(
            old_name="Pereval",
            new_name="MountainPass",
        ),
        migrations.RenameModel(
            old_name="Users",
            new_name="Tourist",
        ),
        migrations.AlterModelOptions(
            name="coord",
            options={"verbose_name": "Coord", "verbose_name_plural": "Coords"},
        ),
        migrations.AlterModelOptions(
            name="mountainpass",
            options={
                "verbose_name": "MountainPass",
                "verbose_name_plural": "MountainPasses",
            },
        ),
        migrations.AlterModelOptions(
            name="tourist",
            options={"verbose_name": "Tourist", "verbose_name_plural": "Tourists"},
        ),
        migrations.RenameField(
            model_name="tourist",
            old_name="patronymic",
            new_name="middle_name",
        ),
    ]
