# Generated by Django 5.0.6 on 2024-06-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_perevaladded_mountainpassadded"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MountainPassAdded",
        ),
    ]
